node {

    def repo_url

    stage('Getting Terraform Scripts') {
        dir('scripts') {
            git url: "https://github.com/jonspandorf/terraform-scripts.git", branch: 'main'
        }
        
    }
    stage('Creating ECR') {
            dir('scripts/create_ecr') {
                sh 'echo "CREATING ECR"'
                sh 'sudo terraform init'
                sh 'sudo terraform apply -auto-approve'
                sh "sudo terraform output the-url | tr -d '\\\"\\\' > ./repo-url.txt "
                repo_url = readFile('./repo-url.txt').trim()
        }
    }
    stage('Creating a Docker image') {
        dir('project') {
            sh 'echo "CREATING A DOCKER IMAGE"'
            git url: "https://github.com/jonspandorf/hello-mobileye.git", branch: 'main'
        }
    }
    stage('Docker Build/Push to ECR') {
        dir('project') {
            sh "sudo docker build -t ${repo_url}:${env.BUILD_NUMBER} ."
            sh "sudo docker push ${repo_url}:${env.BUILD_NUMBER}"
        }
    }
    stage('Create ECS') {

        dir('scripts/create_ecs'){
            sh 'sudo terraform init'
            sh "sudo terraform apply -auto-approve -var='ECR_REPO=${repo_url}' -var='MY_VPC=${VPC_ID}' -var='BUILD_NUMBER=${env.BUILD_NUMBER}'"
        }
    }
}