node {

    def repo_url
    def vpc_id = ''
    def subnets_id = []

    stage('Preparation') {
        dir('scripts') {
            git url: "https://github.com/jonspandorf/terraform-scripts.git", branch: 'main'
        }
        
    }
    stage('build ecr') {
            dir('scripts/create_ecr') {
                sh 'echo "CREATING ECR"'
                sh 'sudo terraform init'
                sh 'sudo terraform apply -auto-approve'
                sh "sudo terraform output the-url | tr -d '\\\"\\\' > ./repo-url.txt "
                repo_url = readFile('./repo-url.txt').trim()
        }
    }
        stage('clone project') {
            dir('project') {
                sh 'echo "CREATING A DOCKER IMAGE"'
                git url: "https://github.com/jonspandorf/hello-mobileye.git", branch: 'main'
            }
        }
        stage('build docker image') {
            dir('project') {
                sh "sudo docker build -t ${repo_url}:1 ."
                sh "sudo docker push ${repo_url}:1"
            }
        }
    stage('create ecs') {

        dir('scripts/create_ecs'){
            sh 'sudo terraform init'
            sh "sudo terraform apply -auto-approve -var='ECR_REPO=${repo_url}' -var='MY_VPC=${vpc_id}' -var='PUBLIC_SUBNETS=${subnets_id}"
        }
    }
}